## GenerativeAI4DS-II
## Healthcare Lab. Question and Answering services

### In this lab you will learn how to implement RAG architectures to process healthcare information and implement Q&A services over medical records

### Get your [OpenAI API Key](https://platform.openai.com/account/api-keys)

In [1]:
OPENAI_API_KEY="YOUR-KEY"

In [2]:
!pip install --upgrade langchain;

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.16)
Requirement already satisfied: langgraph<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.0.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.7.7)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (26.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (4.0.0)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (1.0.8)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (0.3.9)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.1.0,>=1.0.8->langchain) (3.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.0.0)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.8->langchain) (1.12.2)
Requirement already satisfied: httpx>=0.25.2 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.11.5 in /usr/local/lib/python3.12/dist-packages (from langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (0.25.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.4.0,>=0.3.0->langgraph<1.1.0,>=1.0.8->langchain) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.10->langchain) (2.5.0)

In [3]:

!pip install openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.24.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [4]:
!pip install langchain-openai

Requirement already satisfied: langchain-openai in /usr/local/lib/python3.12/dist-packages (1.1.10)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.13 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (1.2.16)
Requirement already satisfied: openai<3.0.0,>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (2.24.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.7.7)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (26.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.14.1)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.20.0->langchain-openai) (4.67.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2025.11.3)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.32.5)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai<3.0.0,>=2.20.0->langchain-openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.20.0->langchain-openai) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.20.0->langchain-openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.20.0->langchain-openai) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.2.13->langchain-openai) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain-openai) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->tiktoken<1.0.0,>=0.7.0->langchain-openai) (2.5.0)

In [5]:
!pip install unstructured

Requirement already satisfied: unstructured in /usr/local/lib/python3.12/dist-packages (0.21.5)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.14.3 in /usr/local/lib/python3.12/dist-packages (from unstructured) (4.14.3)
Requirement already satisfied: charset-normalizer<4.0.0,>=3.4.4 in /usr/local/lib/python3.12/dist-packages (from unstructured) (3.4.4)
Requirement already satisfied: emoji<3.0.0,>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (2.15.0)
Requirement already satisfied: filelock<4.0.0,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (3.24.3)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (1.2.0)
Requirement already satisfied: html5lib<2.0.0,>=1.1 in /usr/local/lib/python3.12/dist-packages (from unstructured) (1.1)
Requirement already satisfied: installer<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (0.7.0)
Requirement already satisfied: langdetect<2.0.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from unstructured) (1.0.9)
Requirement already satisfied: lxml<7.0.0,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (6.0.2)
Requirement already satisfied: numba<1.0.0,>=0.60.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (0.60.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (2.0.2)
Requirement already satisfied: psutil<8.0.0,>=7.2.2 in /usr/local/lib/python3.12/dist-packages (from unstructured) (7.2.2)
Requirement already satisfied: python-iso639<2027.0.0,>=2026.1.31 in /usr/local/lib/python3.12/dist-packages (from unstructured) (2026.1.31)
Requirement already satisfied: python-magic<1.0.0,>=0.4.27 in /usr/local/lib/python3.12/dist-packages (from unstructured) (0.4.27)
Requirement already satisfied: python-oxmsg<1.0.0,>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from unstructured) (0.0.2)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.14.3 in /usr/local/lib/python3.12/dist-packages (from unstructured) (3.14.3)
Requirement already satisfied: regex<2027.0.0,>=2024.0.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (2025.11.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from unstructured) (2.32.5)
Requirement already satisfied: spacy<4.0.0,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (3.8.11)
Requirement already satisfied: tqdm<5.0.0,>=4.67.3 in /usr/local/lib/python3.12/dist-packages (from unstructured) (4.67.3)
Requirement already satisfied: typing-extensions<5.0.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (4.15.0)
Requirement already satisfied: unstructured-client<1.0.0,>=0.25.9 in /usr/local/lib/python3.12/dist-packages (from unstructured) (0.42.10)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from unstructured) (1.17.3)
Requirement already satisfied: soupsieve>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.14.3->unstructured) (2.8.3)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.12/dist-packages (from html5lib<2.0.0,>=1.1->unstructured) (1.17.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from html5lib<2.0.0,>=1.1->unstructured) (0.5.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<1.0.0,>=0.60.0->unstructured) (0.43.0)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from python-oxmsg<1.0.0,>=0.0.2->unstructured) (8.3.1)
Requirement already satisfied: olefile in /usr/local/lib/python3.12/dist-packages (from python-oxmsg<1.0.0,>=0.0.2->unstructured) (0.47)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->unstructured) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->unstructured) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->unstructured) (2026.2.25)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (0.24.0)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy<4.0.0,>=3.7.0->unstructured) (26.0)
Requirement already satisfied: aiofiles>=24.1.0 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (24.1.0)
Requirement already satisfied: cryptography>=3.1 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (43.0.3)
Requirement already satisfied: httpcore>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (1.0.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (0.28.1)
Requirement already satisfied: pypdf>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (6.7.5)
Requirement already satisfied: pypdfium2>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (5.5.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from unstructured-client<1.0.0,>=0.25.9->unstructured) (1.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=3.1->unstructured-client<1.0.0,>=0.25.9->unstructured) (2.0.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore>=1.0.9->unstructured-client<1.0.0,>=0.25.9->unstructured) (0.16.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->unstructured-client<1.0.0,>=0.25.9->unstructured) (4.12.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.7.0->unstructured) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.7.0->unstructured) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy<4.0.0,>=3.7.0->unstructured) (0.4.2)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy<4.0.0,>=3.7.0->unstructured) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy<4.0.0,>=3.7.0->unstructured) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy<4.0.0,>=3.7.0->unstructured) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy<4.0.0,>=3.7.0->unstructured) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy<4.0.0,>=3.7.0->unstructured) (3.0.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=3.1->unstructured-client<1.0.0,>=0.25.9->unstructured) (3.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy<4.0.0,>=3.7.0->unstructured) (0.1.2)

In [6]:
!pip install --upgrade --quiet  "docarray"

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.8/302.8 kB 6.9 MB/s eta 0:00:00

In [7]:
!pip install langchain-community

Collecting langchain-community
  Downloading langchain_community-0.4.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.2.16)
Collecting langchain-classic<2.0.0,>=1.0.0 (from langchain-community)
  Downloading langchain_classic-1.0.1-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.47)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Collecting dataclasses-json<0.7.0,>=0.6.7 (from langchain-community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.13.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.7)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.22.0)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7.0,>=0.6.7->langchain-community)
  Downloading marshmallow-3.26.2-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Collecting langchain-text-splitters<2.0.0,>=1.1.0 (from langchain-classic<2.0.0,>=1.0.0->langchain-community)
  Downloading langchain_text_splitters-1.1.1-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.12.3)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (26.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.0.1->langchain-community) (0.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.1->langchain-community) (3.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community) (2.41.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Downloading langchain_community-0.4.1-py3-none-any.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 20.7 MB/s eta 0:00:00
Downloading dataclasses_json-0.6.7-py3-none-any.whl (28 kB)
Downloading langchain_classic-1.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 27.4 MB/s eta 0:00:00
Downloading langchain_text_splitters-1.1.1-py3-none-any.whl (35 kB)
Downloading marshmallow-3.26.2-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 2.3 MB/s eta 0:00:00
Installing collected packages: marshmallow, dataclasses-json, langchain-text-splitters, langchain-classic, langchain-community
Successfully installed dataclasses-json-0.6.7 langchain-classic-1.0.1 langchain-community-0.4.1 langchain-text-splitters-1.1.1 marshmallow-3.26.2

In [8]:
import os
import openai

In [10]:

!pip install langchain-classic

Requirement already satisfied: langchain-classic in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (1.2.16)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (1.1.1)
Requirement already satisfied: langsmith<1.0.0,>=0.1.17 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (0.7.7)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.12.3)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.32.5)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-classic) (2.0.47)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-classic) (1.33)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-classic) (26.0)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-classic) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-classic) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.5->langchain-classic) (0.14.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (1.0.0)
Requirement already satisfied: xxhash>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.17->langchain-classic) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.0.0->langchain-classic) (2026.2.25)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-classic) (3.3.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.17->langchain-classic) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.5->langchain-classic) (3.0.0)

In [11]:





from langchain_classic.chains import RetrievalQA
from langchain_openai import ChatOpenAI
from langchain_community.document_loaders import DataFrameLoader
from langchain_community.vectorstores import DocArrayInMemorySearch
from IPython.display import display, Markdown
from langchain_openai.llms import OpenAI
import pandas as pd

### 1. Let's load a small subset of medical records

In [12]:
df=pd.read_csv("https://github.com/thousandoaks/Python4DS-I/raw/main/datasets/HealthcareDataset_PublicRelease.csv",sep=',',parse_dates=['StartDate','EndDate','BirthDate'])

In [13]:
pd.options.display.max_colwidth = 300
df.head(20)

,Id,MemberName,MemberID,County,MedicalClaim,ClaimItem,HospitalName,HospitalType,StartDate,EndDate,PrincipalDiagnosisDesc,PrincipalDiagnosis,RevenueCodeDesc,RevenueCode,TypeFlag,BirthDate,TotalExpenses
0,634363,e659f3f4,6a380a28,6f943458,c1e3436737c77899,18,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING,636.0,ER,1967-05-13,15.148
1,634364,e659f3f4,6a380a28,6f943458,c1e3436737c77899,21,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING,636.0,ER,1967-05-13,3.073
2,634387,e659f3f4,6a380a28,6f943458,c1e3436737c77899,10,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY,305.0,ER,1967-05-13,123.900
3,634388,e659f3f4,6a380a28,6f943458,c1e3436737c77899,20,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING,636.0,ER,1967-05-13,7.511
4,634389,e659f3f4,6a380a28,6f943458,c1e3436737c77899,19,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING,636.0,ER,1967-05-13,8.631
5,634390,e659f3f4,6a380a28,6f943458,c1e3436737c77899,2,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY,301.0,ER,1967-05-13,263.200
6,634391,e659f3f4,6a380a28,6f943458,c1e3436737c77899,6,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY,301.0,ER,1967-05-13,44.100
7,634392,e659f3f4,6a380a28,6f943458,c1e3436737c77899,12,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,RADIOLOGY - DIAGNOSTIC: CHEST X-RAY,324.0,ER,1967-05-13,364.000
8,634393,e659f3f4,6a380a28,6f943458,c1e3436737c77899,15,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,EMERGENCY ROOM,450.0,ER,1967-05-13,789.600
9,634394,e659f3f4,6a380a28,6f943458,c1e3436737c77899,17,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,EMERGENCY ROOM,450.0,ER,1967-05-13,478.100
10,634395,e659f3f4,6a380a28,6f943458,c1e3436737c77899,1,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,PHARMACY,250.0,ER,1967-05-13,4.256
11,634396,e659f3f4,6a380a28,6f943458,c1e3436737c77899,3,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY,301.0,ER,1967-05-13,221.900
12,634397,e659f3f4,6a380a28,6f943458,c1e3436737c77899,4,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY,301.0,ER,1967-05-13,199.500
13,634398,e659f3f4,6a380a28,6f943458,c1e3436737c77899,5,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY,301.0,ER,1967-05-13,161.700
14,634399,e659f3f4,6a380a28,6f943458,c1e3436737c77899,16,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,EMERGENCY ROOM,450.0,ER,1967-05-13,594.300
15,634400,e659f3f4,6a380a28,6f943458,c1e3436737c77899,22,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING,636.0,ER,1967-05-13,1.911
16,634401,e659f3f4,6a380a28,6f943458,c1e3436737c77899,23,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,EKG/ECG,730.0,ER,1967-05-13,402.500
17,634402,e659f3f4,6a380a28,6f943458,c1e3436737c77899,9,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY,305.0,ER,1967-05-13,137.200
18,634403,e659f3f4,6a380a28,6f943458,c1e3436737c77899,14,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,EMERGENCY ROOM,450.0,ER,1967-05-13,3549.700
19,634404,e659f3f4,6a380a28,6f943458,c1e3436737c77899,13,04b77561,HOSPITAL,2020-01-08,2020-01-08,Epigastric pain,R10.13,OTHER IMAGING SERVICES: ULTRASOUND,402.0,ER,1967-05-13,805.700

In [14]:
MedicalRecords=df.sort_values(by='MemberName').head(200).groupby(["MedicalClaim","MemberName","PrincipalDiagnosisDesc","PrincipalDiagnosis"]).agg({"TotalExpenses": ["sum"],"RevenueCodeDesc":' '.join}).reset_index()

In [15]:
MedicalRecords.columns

MultiIndex([(          'MedicalClaim',     ''),
            (            'MemberName',     ''),
            ('PrincipalDiagnosisDesc',     ''),
            (    'PrincipalDiagnosis',     ''),
            (         'TotalExpenses',  'sum'),
            (       'RevenueCodeDesc', 'join')],
           )

In [16]:
# We flatten the multindex into a regular DataFrame
MedicalRecords.columns=MedicalRecords.columns.get_level_values(0)

In [17]:
MedicalRecords.head(3)

,MedicalClaim,MemberName,PrincipalDiagnosisDesc,PrincipalDiagnosis,TotalExpenses,RevenueCodeDesc
0,01db6f5467574d6e,00bdc46e,Hypertensive heart diseas,I11.0,111436.402,LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN ...
1,11c6f93bdbb127d8,00f62513,Rectal abscess,K61.1,46470.151,EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN
2,3076d98ae812aec7,00f62513,Abnormal finding of blood,R79.9,4739.028,EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DI...

In [18]:
# prompt: Using dataframe MedicalRecords: count number of different MemberName

MedicalRecords.groupby('MemberName').count()

,MedicalClaim,PrincipalDiagnosisDesc,PrincipalDiagnosis,TotalExpenses,RevenueCodeDesc
MemberName,,,,,
000e9b80,1,1,1,1,1
002451eb,1,1,1,1,1
003e47b4,1,1,1,1,1
00a90ae2,1,1,1,1,1
00bdc46e,3,3,3,3,3
00c10ea4,3,3,3,3,3
00f62513,3,3,3,3,3

In [19]:
MedicalRecords=MedicalRecords.astype(str)

In [20]:
MedicalRecords['MedicalInformation']='MedicalClaim: '+MedicalRecords['MedicalClaim']+ ' # ' +'MemberName: ' +MedicalRecords['MemberName']+ ' # ' +'PrincipalDiagnosisDesc: ' +MedicalRecords['PrincipalDiagnosisDesc']+ ' # ' +'PrincipalDiagnosis: ' +MedicalRecords['PrincipalDiagnosis']+ ' # ' +'TotalExpenses: ' +MedicalRecords['TotalExpenses']+ ' # ' +'RevenueCodeDesc: ' +MedicalRecords['RevenueCodeDesc']

In [21]:
MedicalRecords.head(2)

,MedicalClaim,MemberName,PrincipalDiagnosisDesc,PrincipalDiagnosis,TotalExpenses,RevenueCodeDesc,MedicalInformation
0,01db6f5467574d6e,00bdc46e,Hypertensive heart diseas,I11.0,111436.402,LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN ...,MedicalClaim: 01db6f5467574d6e # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 111436.402 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-R...
1,11c6f93bdbb127d8,00f62513,Rectal abscess,K61.1,46470.151000000005,EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN,MedicalClaim: 11c6f93bdbb127d8 # MemberName: 00f62513 # PrincipalDiagnosisDesc: Rectal abscess # PrincipalDiagnosis: K61.1 # TotalExpenses: 46470.151000000005 # RevenueCodeDesc: EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN

In [22]:
loader = DataFrameLoader(MedicalRecords, page_content_column='MedicalInformation')

In [23]:
MedicalRecordsCatalog=loader.load()

In [24]:
len(MedicalRecordsCatalog)

13

In [25]:
MedicalRecordsCatalog[0]

Document(metadata={'MedicalClaim': '01db6f5467574d6e', 'MemberName': '00bdc46e', 'PrincipalDiagnosisDesc': 'Hypertensive heart diseas', 'PrincipalDiagnosis': 'I11.0', 'TotalExpenses': '111436.402', 'RevenueCodeDesc': 'LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND'}, page_content='MedicalClaim: 01db6f5467574d6e # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 111436.402 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND')

In [26]:
MedicalRecordsCatalog[1]

Document(metadata={'MedicalClaim': '11c6f93bdbb127d8', 'MemberName': '00f62513', 'PrincipalDiagnosisDesc': 'Rectal abscess', 'PrincipalDiagnosis': 'K61.1', 'TotalExpenses': '46470.151000000005', 'RevenueCodeDesc': 'EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN'}, page_content='MedicalClaim: 11c6f93bdbb127d8 # MemberName: 00f62513 # PrincipalDiagnosisDesc: Rectal abscess # PrincipalDiagnosis: K61.1 # TotalExpenses: 46470.151000000005 # RevenueCodeDesc: EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN')

### 2. Let's split these documents

In [28]:
from langchain_text_splitters import RecursiveCharacterTextSplitter
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=0, add_start_index=True
)

In [29]:
MedicalRecordsCatalogItems = text_splitter.split_documents(MedicalRecordsCatalog)

In [30]:
len(MedicalRecordsCatalogItems)

14

In [31]:
MedicalRecordsCatalogItems[0]

Document(metadata={'MedicalClaim': '01db6f5467574d6e', 'MemberName': '00bdc46e', 'PrincipalDiagnosisDesc': 'Hypertensive heart diseas', 'PrincipalDiagnosis': 'I11.0', 'TotalExpenses': '111436.402', 'RevenueCodeDesc': 'LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND', 'start_index': 0}, page_content='MedicalClaim: 01db6f5467574d6e # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 111436.402 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND')

In [32]:
MedicalRecordsCatalogItems[1]

Document(metadata={'MedicalClaim': '11c6f93bdbb127d8', 'MemberName': '00f62513', 'PrincipalDiagnosisDesc': 'Rectal abscess', 'PrincipalDiagnosis': 'K61.1', 'TotalExpenses': '46470.151000000005', 'RevenueCodeDesc': 'EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN', 'start_index': 0}, page_content='MedicalClaim: 11c6f93bdbb127d8 # MemberName: 00f62513 # PrincipalDiagnosisDesc: Rectal abscess # PrincipalDiagnosis: K61.1 # TotalExpenses: 46470.151000000005 # RevenueCodeDesc: EKG/ECG BLOOD STORAGE/PROCESSING ANESTHESIA OPERATING ROOM SERVICES CT SCAN')

In [33]:
MedicalRecordsCatalogItems[2]

Document(metadata={'MedicalClaim': '3076d98ae812aec7', 'MemberName': '00f62513', 'PrincipalDiagnosisDesc': 'Abnormal finding of blood', 'PrincipalDiagnosis': 'R79.9', 'TotalExpenses': '4739.028', 'RevenueCodeDesc': 'EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY', 'start_index': 0}, page_content='MedicalClaim: 3076d98ae812aec7 # MemberName: 00f62513 # PrincipalDiagnosisDesc: Abnormal finding of blood # PrincipalDiagnosis: R79.9 # TotalExpenses: 4739.028 # RevenueCodeDesc: EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY')

### 2. Let's insert the catalog into a Vector Store

In [35]:
from langchain_openai.embeddings import OpenAIEmbeddings
embeddings_model = OpenAIEmbeddings(openai_api_key=OPENAI_API_KEY)

In [36]:
from langchain_community.vectorstores import DocArrayInMemorySearch
db = DocArrayInMemorySearch.from_documents(MedicalRecordsCatalogItems, embeddings_model)

### 3. Let's query the database

In [37]:
query = "EMERGENCY"

In [38]:
docs = db.similarity_search(query,k=10)

In [39]:
len(docs)

10

In [40]:
docs[0]

Document(metadata={'MedicalClaim': '6016589b30e19fd0', 'MemberName': '00c10ea4', 'PrincipalDiagnosisDesc': 'Myalgia unspecified site', 'PrincipalDiagnosis': 'M79.10', 'TotalExpenses': '6728.981', 'RevenueCodeDesc': 'LABORATORY - CLINICAL DIAGNOSTIC DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING EMERGENCY ROOM EKG/ECG MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY EMERGENCY ROOM EMERGENCY ROOM PHARMACY', 'start_index': 0}, page_content='MedicalClaim: 6016589b30e19fd0 # MemberName: 00c10ea4 # PrincipalDiagnosisDesc: Myalgia unspecified site # PrincipalDiagnosis: M79.10 # TotalExpenses: 6728.981 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING EMERGENCY ROOM EKG/ECG MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY EMERGENCY ROOM EMERGENCY ROOM PHARMACY')

In [41]:
docs[1]

Document(metadata={'MedicalClaim': '3076d98ae812aec7', 'MemberName': '00f62513', 'PrincipalDiagnosisDesc': 'Abnormal finding of blood', 'PrincipalDiagnosis': 'R79.9', 'TotalExpenses': '4739.028', 'RevenueCodeDesc': 'EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY', 'start_index': 0}, page_content='MedicalClaim: 3076d98ae812aec7 # MemberName: 00f62513 # PrincipalDiagnosisDesc: Abnormal finding of blood # PrincipalDiagnosis: R79.9 # TotalExpenses: 4739.028 # RevenueCodeDesc: EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY')

In [42]:
docs[2]

Document(metadata={'MedicalClaim': 'd0b551e232e1b6f1', 'MemberName': '00bdc46e', 'PrincipalDiagnosisDesc': 'Hypertensive heart diseas', 'PrincipalDiagnosis': 'I11.0', 'TotalExpenses': '36030.337', 'RevenueCodeDesc': 'PHYSICAL THERAPY: EVALUATION/RE-EVALUATION MEDICAL/SURGICAL SUPPLIES MEDICAL/SURGICAL/GYN LABORATORY - CLINICAL DIAGNOSTIC PHYSICAL THERAPY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY RADIOLOGY - DIAGNOSTIC: CHEST X-RAY LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES EKG/ECG', 'start_index': 0}, page_content='MedicalClaim: d0b551e232e1b6f1 # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 36030.337 # RevenueCodeDesc: PHYSICAL THERAPY: EVALUATION/RE-EVALUATION MEDICAL/SURGICAL SUPPLIES MEDICAL/SURGICAL/GYN LABORATORY - CLINICAL DIAGNOSTIC PHYSICAL THERAPY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY RADIOLOGY - DIAGNOSTIC: CHEST X-RAY LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES EKG/ECG')

In [43]:
docs[3]

Document(metadata={'MedicalClaim': 'f92bb137b39f997b', 'MemberName': '00f62513', 'PrincipalDiagnosisDesc': 'Sepsis unspecified organi', 'PrincipalDiagnosis': 'A41.9', 'TotalExpenses': '115949.302', 'RevenueCodeDesc': 'OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB EKG/ECG RECOVERY ROOM DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING PULMONARY FUNCTION PHARMACY: IV SOLUTIONS PHYSICAL THERAPY BLOOD STORAGE/PROCESSING: BLOOD ADMINISTRATION (EG. TRANSFUSION) ANESTHESIA CT SCAN RADIOLOGY - DIAGNOSTIC: CHEST X-RAY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY BLOOD STORAGE/PROCESSING OPERATING ROOM SERVICES', 'start_index': 0}, page_content='MedicalClaim: f92bb137b39f997b # MemberName: 00f62513 # PrincipalDiagnosisDesc: Sepsis unspecified organi # PrincipalDiagnosis: A41.9 # TotalExpenses: 115949.302 # RevenueCodeDesc: OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB EKG/ECG RECOVERY ROOM DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING PULMONARY FUNCTION PHARMACY: IV SOLUTIONS PHYSICAL THERAPY BLOOD STORAGE/PROCESSING: BLOOD ADMINISTRATION (EG. TRANSFUSION) ANESTHESIA CT SCAN RADIOLOGY - DIAGNOSTIC: CHEST X-RAY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY BLOOD STORAGE/PROCESSING OPERATING ROOM SERVICES')

In [44]:
docs[4]

Document(metadata={'MedicalClaim': '3d3f3e6226e870f9', 'MemberName': '00c10ea4', 'PrincipalDiagnosisDesc': 'Occlusion and stenosis of', 'PrincipalDiagnosis': 'I65.21', 'TotalExpenses': '74796.841', 'RevenueCodeDesc': 'DRUGS REQUIRE SPECIFIC ID: SELF ADMIN DRUGS (INSULIN ADMIN IN EMERGENCY-DIABETES COMA) PHYSICAL THERAPY: EVALUATION/RE-EVALUATION LABORATORY - PATHOLOGY ANESTHESIA DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING OPERATING ROOM SERVICES LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY RECOVERY ROOM INTERMEDIATE ICU MEDICAL/SURGICAL SUPPLIES: OTHER IMPLANTS PHARMACY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES PHARMACY: OTHER MEDICAL/SURGICAL SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY INPATIENT DEMODIALYSIS', 'start_index': 0}, page_content='MedicalClaim: 3d3f3e6226e870f9 # MemberName: 00c10ea4 # PrincipalDiagnosisDesc: Occlusion and stenosis of # PrincipalDiagnosis: I65.21 # TotalExpenses: 74796.841 # RevenueCodeDesc: DRUGS REQUIRE SPECIFIC ID: SELF ADMIN DRUGS (INSULIN ADMIN IN EMERGENCY-DIABETES COMA) PHYSICAL THERAPY: EVALUATION/RE-EVALUATION LABORATORY - PATHOLOGY ANESTHESIA DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING OPERATING ROOM SERVICES LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY RECOVERY ROOM INTERMEDIATE ICU MEDICAL/SURGICAL SUPPLIES: OTHER IMPLANTS PHARMACY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES PHARMACY: OTHER MEDICAL/SURGICAL SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY INPATIENT DEMODIALYSIS')

In [45]:
docs[5]

Document(metadata={'MedicalClaim': 'fe3763cb500a3328', 'MemberName': '00c10ea4', 'PrincipalDiagnosisDesc': 'Chest pain unspecified', 'PrincipalDiagnosis': 'R07.9', 'TotalExpenses': '21864.479', 'RevenueCodeDesc': 'EKG/ECG LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB INPATIENT DEMODIALYSIS MEDICAL/SURGICAL/GYN MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY TREATMENT/OBSERVATION ROOM: OBSERVATION ROOM CLINIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY RADIOLOGY - DIAGNOSTIC: CHEST X-RAY EMERGENCY ROOM PHARMACY: OTHER LABORATORY - CLINICAL DIAGNOSTIC', 'start_index': 0}, page_content='MedicalClaim: fe3763cb500a3328 # MemberName: 00c10ea4 # PrincipalDiagnosisDesc: Chest pain unspecified # PrincipalDiagnosis: R07.9 # TotalExpenses: 21864.479 # RevenueCodeDesc: EKG/ECG LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB INPATIENT DEMODIALYSIS MEDICAL/SURGICAL/GYN MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY TREATMENT/OBSERVATION ROOM: OBSERVATION ROOM CLINIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY RADIOLOGY - DIAGNOSTIC: CHEST X-RAY EMERGENCY ROOM PHARMACY: OTHER LABORATORY - CLINICAL DIAGNOSTIC')

In [46]:
docs[6]

Document(metadata={'MedicalClaim': '01db6f5467574d6e', 'MemberName': '00bdc46e', 'PrincipalDiagnosisDesc': 'Hypertensive heart diseas', 'PrincipalDiagnosis': 'I11.0', 'TotalExpenses': '111436.402', 'RevenueCodeDesc': 'LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND', 'start_index': 0}, page_content='MedicalClaim: 01db6f5467574d6e # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 111436.402 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND')

In [47]:
docs[7]

Document(metadata={'MedicalClaim': 'bd40b943533deb7b', 'MemberName': '002451eb', 'PrincipalDiagnosisDesc': 'Chronic atrial fibrillati', 'PrincipalDiagnosis': 'I48.20', 'TotalExpenses': '23153.564000000002', 'RevenueCodeDesc': 'LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PREVENTIVE CARE SERVICES: ADMIN. OF VACCINE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY EKG/ECG TREATMENT/OBSERVATION ROOM: OBSERVATION ROOM RADIOLOGY - DIAGNOSTIC: CHEST X-RAY EKG/ECG LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY CARDIOLOGY: ECHOCARDIOLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING OTHER THERAPEUTIC SERV LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY PHARMACY PHARMACY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY', 'start_index': 1000}, page_content='- CLINICAL DIAGNOSTIC: CHEMISTRY PHARMACY PHARMACY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY')

In [48]:
docs[8]

Document(metadata={'MedicalClaim': '3da6d9035cb53f0d', 'MemberName': '00a90ae2', 'PrincipalDiagnosisDesc': 'Open bite of right hand i', 'PrincipalDiagnosis': 'S61.451A', 'TotalExpenses': '9587.557', 'RevenueCodeDesc': 'LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC PREVENTIVE CARE SERVICES: ADMIN. OF VACCINE IV THERAPY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY', 'start_index': 0}, page_content='MedicalClaim: 3da6d9035cb53f0d # MemberName: 00a90ae2 # PrincipalDiagnosisDesc: Open bite of right hand i # PrincipalDiagnosis: S61.451A # TotalExpenses: 9587.557 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC PREVENTIVE CARE SERVICES: ADMIN. OF VACCINE IV THERAPY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY')

In [49]:
docs[9]

Document(metadata={'MedicalClaim': '8cc4cd548a13b44b', 'MemberName': '00bdc46e', 'PrincipalDiagnosisDesc': 'Incisional hernia with ob', 'PrincipalDiagnosis': 'K43.0', 'TotalExpenses': '35680.729', 'RevenueCodeDesc': 'MEDICAL/SURGICAL SUPPLIES MEDICAL/SURGICAL/GYN DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY RADIOLOGY - DIAGNOSTIC CT SCAN PHARMACY PHYSICAL THERAPY: VISIT CHARGE EKG/ECG PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY', 'start_index': 0}, page_content='MedicalClaim: 8cc4cd548a13b44b # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Incisional hernia with ob # PrincipalDiagnosis: K43.0 # TotalExpenses: 35680.729 # RevenueCodeDesc: MEDICAL/SURGICAL SUPPLIES MEDICAL/SURGICAL/GYN DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY RADIOLOGY - DIAGNOSTIC CT SCAN PHARMACY PHYSICAL THERAPY: VISIT CHARGE EKG/ECG PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY')

### 4. Let's implement a retriever

In [50]:
retriever = db.as_retriever()

In [51]:
qdocs = "\n\n".join([docs[i].page_content for i in range(len(docs))])

In [52]:
print(qdocs)

MedicalClaim: 6016589b30e19fd0 # MemberName: 00c10ea4 # PrincipalDiagnosisDesc: Myalgia unspecified site # PrincipalDiagnosis: M79.10 # TotalExpenses: 6728.981 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING EMERGENCY ROOM EKG/ECG MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY EMERGENCY ROOM EMERGENCY ROOM PHARMACY

MedicalClaim: 3076d98ae812aec7 # MemberName: 00f62513 # PrincipalDiagnosisDesc: Abnormal finding of blood # PrincipalDiagnosis: R79.9 # TotalExpenses: 4739.028 # RevenueCodeDesc: EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY

MedicalClaim: d0b551e232e1b6f1 # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 36030.337 # RevenueCodeDesc: PHYSICAL THERAPY: EVALUATION/RE-EVALUATION MEDICAL/SURGICAL SUPPLIES MEDICAL/SURGICAL/GYN LABORATORY - CLINICAL DIAGNOSTIC PHYSICAL THERAPY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY RADIOLOGY - DIAGNOSTIC: CHEST X-RAY LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES EKG/ECG

MedicalClaim: f92bb137b39f997b # MemberName: 00f62513 # PrincipalDiagnosisDesc: Sepsis unspecified organi # PrincipalDiagnosis: A41.9 # TotalExpenses: 115949.302 # RevenueCodeDesc: OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB EKG/ECG RECOVERY ROOM DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING PULMONARY FUNCTION PHARMACY: IV SOLUTIONS PHYSICAL THERAPY BLOOD STORAGE/PROCESSING: BLOOD ADMINISTRATION (EG. TRANSFUSION) ANESTHESIA CT SCAN RADIOLOGY - DIAGNOSTIC: CHEST X-RAY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY BLOOD STORAGE/PROCESSING OPERATING ROOM SERVICES

MedicalClaim: 3d3f3e6226e870f9 # MemberName: 00c10ea4 # PrincipalDiagnosisDesc: Occlusion and stenosis of # PrincipalDiagnosis: I65.21 # TotalExpenses: 74796.841 # RevenueCodeDesc: DRUGS REQUIRE SPECIFIC ID: SELF ADMIN DRUGS (INSULIN ADMIN IN EMERGENCY-DIABETES COMA) PHYSICAL THERAPY: EVALUATION/RE-EVALUATION LABORATORY - PATHOLOGY ANESTHESIA DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING OPERATING ROOM SERVICES LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY RECOVERY ROOM INTERMEDIATE ICU MEDICAL/SURGICAL SUPPLIES: OTHER IMPLANTS PHARMACY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES PHARMACY: OTHER MEDICAL/SURGICAL SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY INPATIENT DEMODIALYSIS

MedicalClaim: fe3763cb500a3328 # MemberName: 00c10ea4 # PrincipalDiagnosisDesc: Chest pain unspecified # PrincipalDiagnosis: R07.9 # TotalExpenses: 21864.479 # RevenueCodeDesc: EKG/ECG LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY OTHER DIAGNOSTIC SERVICES: PERIPHERAL VASCULAR LAB INPATIENT DEMODIALYSIS MEDICAL/SURGICAL/GYN MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY TREATMENT/OBSERVATION ROOM: OBSERVATION ROOM CLINIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY RADIOLOGY - DIAGNOSTIC: CHEST X-RAY EMERGENCY ROOM PHARMACY: OTHER LABORATORY - CLINICAL DIAGNOSTIC

MedicalClaim: 01db6f5467574d6e # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Hypertensive heart diseas # PrincipalDiagnosis: I11.0 # TotalExpenses: 111436.402 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY MEDICAL/SURGICAL/GYN PULMONARY FUNCTION RADIOLOGY - DIAGNOSTIC: CHEST X-RAY PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY RESPIRATORY SERVICES EMERGENCY ROOM CT SCAN: HEAD LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY CT SCAN LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC RADIOLOGY - DIAGNOSTIC PHYSICAL THERAPY: VISIT CHARGE LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY INTERMEDIATE ICU DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: IMMUNOLOGY EKG/ECG MEDICAL/SURGICAL SUPPLIES OTHER IMAGING SERVICES: ULTRASOUND

- CLINICAL DIAGNOSTIC: CHEMISTRY PHARMACY PHARMACY PHARMACY MEDICAL/SURGICAL SUPPLIES: STERILE SUPPLIES LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY

MedicalClaim: 3da6d9035cb53f0d # MemberName: 00a90ae2 # PrincipalDiagnosisDesc: Open bite of right hand i # PrincipalDiagnosis: S61.451A # TotalExpenses: 9587.557 # RevenueCodeDesc: LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: BACTERIOLOGY/MICROBIOLOGY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC PREVENTIVE CARE SERVICES: ADMIN. OF VACCINE IV THERAPY DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY

MedicalClaim: 8cc4cd548a13b44b # MemberName: 00bdc46e # PrincipalDiagnosisDesc: Incisional hernia with ob # PrincipalDiagnosis: K43.0 # TotalExpenses: 35680.729 # RevenueCodeDesc: MEDICAL/SURGICAL SUPPLIES MEDICAL/SURGICAL/GYN DRUGS REQUIRE SPECIFIC ID: DRUGS REQUIRING DETAIL CODING LABORATORY - CLINICAL DIAGNOSTIC EMERGENCY ROOM LABORATORY - CLINICAL DIAGNOSTIC: CHEMISTRY LABORATORY - CLINICAL DIAGNOSTIC: HEMATOLOGY LABORATORY - CLINICAL DIAGNOSTIC: UROLOGY RADIOLOGY - DIAGNOSTIC CT SCAN PHARMACY PHYSICAL THERAPY: VISIT CHARGE EKG/ECG PHYSICAL THERAPY: EVALUATION/RE-EVALUATION PHYSICAL THERAPY

In [53]:
llm = ChatOpenAI(temperature=0.0, model='gpt-4-0125-preview',openai_api_key=OPENAI_API_KEY)

## 5. Let's formulate a query

In [54]:
response = llm.invoke(f"the following document lists Medical Events involving Emergency Room services. Your tasks are: \
(1) extract *ALL* events with medical code I11.0, (2) for each event extract the Membername and TotalExpenses, \
(3) for event provide a 1 paragraph summary of RevenueCodeDesc {qdocs}")

In [55]:
response

AIMessage(content="From the provided document, there are two medical events involving Emergency Room services with the medical code I11.0. The details extracted for each event are as follows:\n\n1. **Medical Claim: d0b551e232e1b6f1**\n   - **Member Name:** 00bdc46e\n   - **Total Expenses:** 36030.337\n\n   This medical event involved a member diagnosed with Hypertensive heart disease (I11.0), incurring total expenses of $36,030.337. The services rendered included a variety of diagnostic and therapeutic procedures such as physical therapy, laboratory diagnostics covering bacteriology/microbiology, hematology, chemistry, emergency room services, radiology for chest X-ray, EKG/ECG, and the provision of medical/surgical supplies including sterile supplies. The comprehensive care suggests a significant intervention was required to manage the member's condition, involving both diagnostic assessments and therapeutic management to address the complexities of hypertensive heart disease.\n\n2. **Medical Claim: 01db6f5467574d6e**\n   - **Member Name:** 00bdc46e\n   - **Total Expenses:** 111436.402\n\n   This medical event also pertains to a member diagnosed with Hypertensive heart disease (I11.0), with the event incurring a total of $111,436.402 in expenses. The treatment included a wide array of services such as emergency room visits, physical therapy evaluations and sessions, respiratory services, radiology including chest X-ray and CT scans, laboratory diagnostics across various specialties (bacteriology/microbiology, hematology, chemistry, immunology, urology), pharmacy services, and the use of medical/surgical supplies. The high expenses and diverse range of services indicate an extensive and possibly complicated medical intervention, highlighting the severity of the member's hypertensive heart condition and the multidisciplinary approach taken for treatment.", additional_kwargs={'refusal': None}, response_metadata={'token_usage': {'completion_tokens': 392, 'prompt_tokens': 2236, 'total_tokens': 2628, 'completion_tokens_details': {'accepted_prediction_tokens': 0, 'audio_tokens': 0, 'reasoning_tokens': 0, 'rejected_prediction_tokens': 0}, 'prompt_tokens_details': {'audio_tokens': 0, 'cached_tokens': 0}}, 'model_provider': 'openai', 'model_name': 'gpt-4-0125-preview', 'system_fingerprint': None, 'id': 'chatcmpl-DG99pbDgCQrBOgh5udCDcPUANmeo3', 'service_tier': 'default', 'finish_reason': 'stop', 'logprobs': None}, id='lc_run--019cbf96-42be-7410-83d3-f457258b5786-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 2236, 'output_tokens': 392, 'total_tokens': 2628, 'input_token_details': {'audio': 0, 'cache_read': 0}, 'output_token_details': {'audio': 0, 'reasoning': 0}})

In [57]:
display(Markdown(response.content))

From the provided document, there are two medical events involving Emergency Room services with the medical code I11.0. The details extracted for each event are as follows:

1. **Medical Claim: d0b551e232e1b6f1**
   - **Member Name:** 00bdc46e
   - **Total Expenses:** 36030.337

   This medical event involved a member diagnosed with Hypertensive heart disease (I11.0), incurring total expenses of $36,030.337. The services rendered included a variety of diagnostic and therapeutic procedures such as physical therapy, laboratory diagnostics covering bacteriology/microbiology, hematology, chemistry, emergency room services, radiology for chest X-ray, EKG/ECG, and the provision of medical/surgical supplies including sterile supplies. The comprehensive care suggests a significant intervention was required to manage the member's condition, involving both diagnostic assessments and therapeutic management to address the complexities of hypertensive heart disease.

2. **Medical Claim: 01db6f5467574d6e**
   - **Member Name:** 00bdc46e
   - **Total Expenses:** 111436.402

   This medical event also pertains to a member diagnosed with Hypertensive heart disease (I11.0), with the event incurring a total of $111,436.402 in expenses. The treatment included a wide array of services such as emergency room visits, physical therapy evaluations and sessions, respiratory services, radiology including chest X-ray and CT scans, laboratory diagnostics across various specialties (bacteriology/microbiology, hematology, chemistry, immunology, urology), pharmacy services, and the use of medical/surgical supplies. The high expenses and diverse range of services indicate an extensive and possibly complicated medical intervention, highlighting the severity of the member's hypertensive heart condition and the multidisciplinary approach taken for treatment.

## 6. Let's formulate another query

In [58]:
response = llm.invoke(f"the following document lists Medical Events involving Emergency Room services. Your tasks are: \
(1) compute total expenses {qdocs}")

In [59]:
display(Markdown(response.content))

To compute the total expenses from the provided medical claims, we will sum up the TotalExpenses values from each claim.

1. **Myalgia unspecified site**: $6,728.981
2. **Abnormal finding of blood**: $4,739.028
3. **Hypertensive heart disease (d0b551e232e1b6f1)**: $36,030.337
4. **Sepsis unspecified organi**: $115,949.302
5. **Occlusion and stenosis of**: $74,796.841
6. **Chest pain unspecified**: $21,864.479
7. **Hypertensive heart disease (01db6f5467574d6e)**: $111,436.402
8. **Open bite of right hand i**: $9,587.557
9. **Incisional hernia with ob**: $35,680.729

Adding these amounts together gives the total expenses:

\[6,728.981 + 4,739.028 + 36,030.337 + 115,949.302 + 74,796.841 + 21,864.479 + 111,436.402 + 9,587.557 + 35,680.729 = \]

\[416,813.656\]

Therefore, the total expenses from all the medical claims listed is $416,813.656.